
CREATE TABLE [dbo].[QuantityTypes](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nchar](10) NULL,
 CONSTRAINT [PK_QuantityTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


